require:
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-thread_safety

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - bin/**
    - db/schema.rb

Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - Gemfile

Metrics/MethodLength:
  Exclude:
    - db/migrate/**
  Max: 50

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 100

# rubocop-i18n
RailsI18n:
  Enabled: true
GetText:
  Enabled: false
