require:
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable
  Exclude:
    - vendor/**/*
    - bin/**
    - db/schema.rb

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - Gemfile

Metrics/MethodLength:
  Exclude:
    - db/migrate/**
  Max: 50

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Layout/LineLength:
  Max: 100

# rubocop-i18n
RailsI18n:
  Enabled: true
GetText:
  Enabled: false

# rubocop-rspec
RSpec/ExampleLength:
  Max: 20
